services:
  - type: web
    name: rcikent-website-be
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGO_URL
        sync: false
      - key: DB_NAME
        value: rcikent_db
      - key: CORS_ORIGINS
        value: https://kaffadu.github.io,http://localhost:3000
      - key: PYTHON_VERSION
        value: "3.11"
      - key: RESEND_API_KEY
        sync: false
      - key: NOTIFY_EMAIL
        sync: false
